# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs: 
  unit-test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
         path: ~/.npm
         key: npm-${{ hashFiles('package-lock.json') }}
         restore-keys: npm-
      - name: Prep NPM dependencies
        run: npm install 
      
      - name: Test NPM test
        run: npm run test

      - name: Test NPM test
        run: |
          npm install -f
          npm run test:unit:coverage:ci

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.0.8
        with:
          skip-step: all
          coverage-file: ./test/unit/coverage/report.json
          base-coverage-file: ./test/unit/coverage/report.json
